# Use the official .NET 10 SDK image for building
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /app

# Copy project files
COPY ./ ./ 

# Restore dependencies
RUN dotnet restore

# Build in Release mode
RUN dotnet build -c Release --no-restore

# Optional: run unit tests
# RUN dotnet test --no-restore -c Release

# Use smaller runtime image
FROM mcr.microsoft.com/dotnet/runtime:10.0 AS runtime
WORKDIR /app

# Copy compiled output from build stage
COPY --from=build /app/bin/Release/net10/ ./ 

# Set entrypoint to run the console app
ENTRYPOINT ["dotnet", "Samwin.UmlautConverter.ConsoleApp.Client.exe"]